log:
  level: debug
  disable_sentry: true

db:
  url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bi-db:5432/${POSTGRES_DB}?sslmode=disable

listener:
  addr: :8800

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: btc-indexer-svc
  service_port: 80

signer:
  jwt_secret: "a-string-secret-at-least-256-bits-long"