services:
  bi-db:
    image: postgres:17.6
    container_name: bi-svc-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /pgdata
    volumes:
      - bi-data:/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  bi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bi-svc
    depends_on:
      bi-db:
        condition: service_healthy
    environment:
      KV_VIPER_FILE: /config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - "8800:8800"
    entrypoint: sh -c "btc-indexer-svc migrate up && btc-indexer-svc run service"

volumes:
  bi-data: